# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish_Win_x86
      run: dotnet publish Hamster -p:PublishProfile=/home/runner/work/HamsterFramework/HamsterFramework/Hamster/Properties/PublishProfiles/win-x86.pubxml
    - name: Publish_Win_x64
      run: dotnet publish Hamster -p:PublishProfile=/home/runner/work/HamsterFramework/HamsterFramework/Hamster/Properties/PublishProfiles/win-x64.pubxml
    - name: Publish_Win_arm
      run: dotnet publish Hamster -p:PublishProfile=./Hamster/Properties/PublishProfiles/win-arm.pubxml
    - name: Publish_Win_arm64
      run: dotnet publish Hamster -p:PublishProfile=./Hamster/Properties/PublishProfiles/win-arm64.pubxml
    - name: Publish_Linux_x64
      run: dotnet publish Hamster -p:PublishProfile=./Hamster/Properties/PublishProfiles/linux-x64.pubxml
    - name: Publish_Linux_arm
      run: dotnet publish Hamster -p:PublishProfile=./Hamster/Properties/PublishProfiles/linux-arm.pubxml
    - name: Publish_Linux_arm64
      run: dotnet publish Hamster -p:PublishProfile=./Hamster/Properties/PublishProfiles/linux-arm64.pubxml
    
