# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      shell: bash
      run: dotnet restore
      
    - name: Build
      shell: bash
      run: dotnet build --no-restore
      
    - name: Test
      shell: bash
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish_Win_x86
      shell: bash
      run: dotnet publish Hamster -p:PublishProfile=win-x86
      
    - name: Publish_Win_x64
      shell: bash
      run: dotnet publish Hamster -p:PublishProfile=win-x64
      
    - name: Publish_Win_arm
      shell: bash
      run: dotnet publish Hamster -p:PublishProfile=win-arm
      
    - name: Publish_Win_arm64
      shell: bash
      run: dotnet publish Hamster -p:PublishProfile=win-arm64
      
    - name: Publish_Linux_x64
      shell: bash
      run: dotnet publish Hamster -p:PublishProfile=linux-x64
      
    - name: Publish_Linux_arm
      shell: bash
      run: dotnet publish Hamster -p:PublishProfile=linux-arm
      
    - name: Publish_Linux_arm64
      shell: bash
      run: dotnet publish Hamster -p:PublishProfile=linux-arm64
    
