# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish_Win_x86
      run: dotnet publish Hamster/Hamster.csproj -p:Configuration=Release -p:SelfContained=true -p:PublishDir=publish/win-x86/ -p:RuntimeIdentifier=win-x86
      
    - name: Publish_Win_x64
      run: dotnet publish Hamster -p:Configuration=Release -p:SelfContained=true -p:PublishDir=publish/win-x64/ -p:RuntimeIdentifier=win-x64
      
    - name: Publish_Win_arm
      run: dotnet publish Hamster -p:Configuration=Release -p:SelfContained=true -p:PublishDir=publish/win-arm/ -p:RuntimeIdentifier=win-arm
      
    - name: Publish_Win_arm64
      run: dotnet publish Hamster -p:Configuration=Release -p:SelfContained=true -p:PublishDir=publish/win-arm64/ -p:RuntimeIdentifier=win-arm64
      
    - name: Publish_Linux_x64
      run: dotnet publish Hamster -p:Configuration=Release -p:SelfContained=true -p:PublishDir=publish/linux-x64/ -p:RuntimeIdentifier=linux-x64
      
    - name: Publish_Linux_arm
      run: dotnet publish Hamster -p:Configuration=Release -p:SelfContained=true -p:PublishDir=publish/linux-arm/ -p:RuntimeIdentifier=linux-arm
      
    - name: Publish_Linux_arm64
      run: dotnet publish Hamster -p:Configuration=Release -p:SelfContained=true -p:PublishDir=publish/linux-arm64/ -p:RuntimeIdentifier=linux-arm64
    
