# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Publish_Win_x86
      run: |
        cd ./Hamster
        dotnet publish -p:PublishProfile=win-x86
        zip -qr win-x86.zip bin/Release/net7.0/publish/win-x86/
      
    - name: Publish_Win_x64
      run: |
        cd ./Hamster
        dotnet publish -p:PublishProfile=win-x64
        zip -qr win-x64.zip bin/Release/net7.0/publish/win-x64/
      
    - name: Publish_Win_arm
      run: |
       cd ./Hamster
       dotnet publish -p:PublishProfile=win-arm
       zip -qr win-arm.zip bin/Release/net7.0/publish/win-arm/
      
    - name: Publish_Win_arm64
      run: |
        cd ./Hamster
        dotnet publish -p:PublishProfile=win-arm64
        zip -qr win-arm64.zip bin/Release/net7.0/publish/win-arm64/
      
    - name: Publish_Linux_x64
      run: |
        cd ./Hamster
        dotnet publish -p:PublishProfile=linux-x64
        zip -qr linux-x64.zip bin/Release/net7.0/publish/linux-x64/
      
    - name: Publish_Linux_arm
      run: |
        cd ./Hamster
        dotnet publish -p:PublishProfile=linux-arm
        zip -qr linux-arm.zip bin/Release/net7.0/publish/linux-arm/
      
    - name: Publish_Linux_arm64
      run: |
        cd ./Hamster
        dotnet publish -p:PublishProfile=linux-arm64
        zip -qr linux-arm64.zip bin/Release/net7.0/publish/linux-arm64/
    
    - name: List files
      run: |
        cd ./Hamster
        ls
        echo ${{ github.ref }}
        echo ${{ vars.VERSION }}
        echo ${{ vars.PRERELEASE }}
        echo ${{ vars.PUBLISH }}
        echo ${{ vars.BODY }}
    - name: Create release
      if: ${{ vars.PUBLISH == "true" }}
      uses: svenstaro/upload-release-action@2.5.0
      with:
        repo_token: ${{ secrets.TOKEN }}
        file:  ./Hamster/*.zip
        tag: ${{ vars.VERSION }}
        release_name: ${{ vars.VERSION }}
        overwrite: false
        file_glob: true
        prerelease: ${{ vars.PRERELEASE == "true" }}
        body: ${{ vars.BODY }}
